/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.30.1.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import * as _0 from "./Marketplace.types";
import * as _1 from "./Marketplace.client";
import * as _2 from "./Marketplace.message-composer";
import * as _3 from "./ReserveAuction.types";
import * as _4 from "./ReserveAuction.client";
import * as _5 from "./ReserveAuction.message-composer";
export namespace contracts {
  export const Marketplace = { ..._0,
    ..._1,
    ..._2
  };
  export const ReserveAuction = { ..._3,
    ..._4,
    ..._5
  };
}