[package]
name        = "sg-marketplace-common"
version     = "1.0.0"
authors     = ["Shane Vitarana <s@noreply.publicawesome.com>"]
description = "Common functionality used in Marketplace contracts"
edition     = { workspace = true }
homepage    = { workspace = true }
repository  = { workspace = true }
license     = { workspace = true }

exclude = [
  # Those files are rust-optimizer artifacts. You might want to commit them for convenience but they should not be part of the source code publication.
  "contract.wasm",
  "hash.txt",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]

[features]
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces"]
# use library feature to disable all instantiate/execute/query exports
library = []

[dependencies]
cosmwasm-schema  = { workspace = true }
cosmwasm-std     = { workspace = true }
cosmwasm-storage = { workspace = true }
cw-storage-macro = { workspace = true }
cw-storage-plus  = { workspace = true }
cw-utils         = { workspace = true }
cw2              = { workspace = true }
cw721            = { workspace = true }
cw721-base       = { workspace = true }
sg721-base       = { workspace = true }
sg721            = { workspace = true }
schemars         = { workspace = true }
serde            = { workspace = true }
sg-std           = { workspace = true }
sg1              = { workspace = true }
sg-fair-burn     = { workspace = true }
thiserror        = { workspace = true }

[dev-dependencies]
cw-multi-test = { workspace = true }
sg-multi-test = { workspace = true }
test-suite    = { workspace = true }
base-minter   = { workspace = true }
mockall       = { workspace = true }
